# Form implementation generated from reading ui file 'administracionusuario.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaAdministracionUsuario(object):
    def setupUi(self, ventanaAdministracionUsuario):
        ventanaAdministracionUsuario.setObjectName("ventanaAdministracionUsuario")
        ventanaAdministracionUsuario.resize(845, 584)
        ventanaAdministracionUsuario.setMinimumSize(QtCore.QSize(845, 584))
        ventanaAdministracionUsuario.setMaximumSize(QtCore.QSize(845, 584))

        #########pocisionar ventana centrada#####
        qr = ventanaAdministracionUsuario.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaAdministracionUsuario.move(qr.topLeft())
        #######################################
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/configuracion.jpeg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaAdministracionUsuario.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaAdministracionUsuario)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 843, 582))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(1, 1, 841, 35))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.toolBar = QtWidgets.QToolBar(self.groupBox_3)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/03.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/04.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/21.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/printer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        
        self.actionAdd = QtGui.QAction(self)
        self.actionAdd.setIcon(icon1)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtGui.QAction(self)
        self.actionDelete.setIcon(icon2)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEdit = QtGui.QAction(self)
        self.actionEdit.setIcon(icon3)
        self.actionEdit.setObjectName("actionEdit")
        self.actionPrint = QtGui.QAction(self)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")

        self.tableUsuario = QtWidgets.QTableWidget(self.groupBox)
        self.tableUsuario.setGeometry(QtCore.QRect(1, 39, 841, 541))
        self.tableUsuario.setColumnCount(5)
        self.tableUsuario.setObjectName("tableUsuario")
        self.tableUsuario.setRowCount(0)
        self.tableUsuario.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableUsuario.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableUsuario.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableUsuario.verticalHeader().setVisible(False)
        self.tableUsuario.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tableUsuario.customContextMenuRequested.connect(self.contexMenuEvent)


        #ancho de las columnas
        self.tableUsuario.setColumnWidth(0,10)
        self.tableUsuario.setColumnWidth(1,250)
        self.tableUsuario.setColumnWidth(2,389)
        self.tableUsuario.setColumnWidth(3,200)
        self.tableUsuario.setColumnWidth(4,150)

        self.tableUsuario.setColumnHidden(0, True)
        self.tableUsuario.setColumnHidden(4, True)
        #cabecera de la tabla
        self.headerTablaUsuario()

        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(ventanaAdministracionUsuario)
        QtCore.QMetaObject.connectSlotsByName(ventanaAdministracionUsuario)

        #### eventos de los botones
        self.actionAdd.triggered.connect(self.nuevoUsuario)
        self.actionEdit.triggered.connect(self.editarUsuario)
        self.actionDelete.triggered.connect(self.eliminarUsuario)
        self.actionPrint.triggered.connect(self.vistaPrevia)
        self.tableUsuario.clicked.connect(self.usuarioSeleccionado)
        self.tableUsuario.doubleClicked.connect(self.editarUsuario) 

    def retranslateUi(self, ventanaAdministracionUsuario):
        _translate = QtCore.QCoreApplication.translate
        ventanaAdministracionUsuario.setWindowTitle(_translate("ventanaAdministracionUsuario", "Administración de Usuarios"))
        self.actionAdd.setText(_translate("ventanaAdministracionUsuario", "Agregar Usuario"))
        self.actionDelete.setText(_translate("ventanaAdministracionUsuario", "Eliminar Usuario"))
        self.actionEdit.setText(_translate("ventanaAdministracionUsuario", "Editar Usuario"))
        self.actionPrint.setText(_translate("ventanaAdministracionUsuario", "Imprimir lista de Usuarios"))

        self.inicializarVentana()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaAdministracionUsuario = QtWidgets.QDialog()
    ui = Ui_VentanaAdministracionUsuario()
    ui.setupUi(ventanaAdministracionUsuario)
    ventanaAdministracionUsuario.show()
    sys.exit(app.exec())
