# Form implementation generated from reading ui file 'QtForm/acerca.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaAcerca(object):
    def setupUi(self, ventanaAcerca):
        ventanaAcerca.setObjectName("ventanaAcerca")
        ventanaAcerca.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        ventanaAcerca.resize(432, 300)
        ventanaAcerca.setMinimumSize(QtCore.QSize(432, 300))
        ventanaAcerca.setMaximumSize(QtCore.QSize(432, 300))

        #########pocisionar ventana centrada#####
        qr = ventanaAcerca.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaAcerca.move(qr.topLeft())
        #######################################
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/About.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaAcerca.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(ventanaAcerca)
        self.label.setGeometry(QtCore.QRect(83, 14, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ventanaAcerca)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 241, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ventanaAcerca)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 271, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ventanaAcerca)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 221, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ventanaAcerca)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 321, 19))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(ventanaAcerca)
        self.pushButton.setGeometry(QtCore.QRect(180, 250, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ventanaAcerca)
        QtCore.QMetaObject.connectSlotsByName(ventanaAcerca)

        self.pushButton.clicked.connect(lambda:self.cerrarVentana(ventanaAcerca))

    def retranslateUi(self, ventanaAcerca):
        _translate = QtCore.QCoreApplication.translate
        ventanaAcerca.setWindowTitle(_translate("ventanaAcerca", "Acerca de"))
        self.label.setText(_translate("ventanaAcerca", "Control de Talleres"))
        self.label_2.setText(_translate("ventanaAcerca", "Version: 1.0"))
        self.label_3.setText(_translate("ventanaAcerca", "Creador: Arnel González Rodríguez"))
        self.label_4.setText(_translate("ventanaAcerca", "Teéfono: 54579981"))
        self.label_5.setText(_translate("ventanaAcerca", "Correo electrńico: arnel.glez@gmail.com"))
        self.pushButton.setText(_translate("ventanaAcerca", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaAcerca = QtWidgets.QventanaAcerca()
    ui = Ui_VentanaAcerca()
    ui.setupUi(ventanaAcerca)
    ventanaAcerca.show()
    sys.exit(app.exec())
