# Form implementation generated from reading ui file 'QtForm/buscarfactura.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaBuscarFactura(object):
    def setupUi(self, ventanaBuscarFactura):
        ventanaBuscarFactura.setObjectName("ventanaBuscarFactura")
        ventanaBuscarFactura.resize(480, 480)
        ventanaBuscarFactura.setMinimumSize(QtCore.QSize(480, 480))
        ventanaBuscarFactura.setMaximumSize(QtCore.QSize(480, 480)) 

        #########pocisionar ventana centrada#####
        qr = ventanaBuscarFactura.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaBuscarFactura.move(qr.topLeft())
        #######################################

        ventanaBuscarFactura.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Factura.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaBuscarFactura.setWindowIcon(icon)
        self.groupBox_3 = QtWidgets.QGroupBox(ventanaBuscarFactura)
        self.groupBox_3.setGeometry(QtCore.QRect(1, 430, 478, 48))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonAceptar.setGeometry(QtCore.QRect(130, 11, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonAceptar.setEnabled(False)
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonCancelar.setGeometry(QtCore.QRect(290, 11, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.groupBox = QtWidgets.QGroupBox(ventanaBuscarFactura)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 478, 50))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.editFactura = QtWidgets.QLineEdit(self.groupBox)
        self.editFactura.setGeometry(QtCore.QRect(10, 16, 460, 22))
        self.editFactura.setObjectName("editFactura")
        self.groupBox_2 = QtWidgets.QGroupBox(ventanaBuscarFactura)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 50, 478, 380))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1, 5, 476, 374))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableFactura = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableFactura.setColumnCount(3)
        self.tableFactura.setObjectName("tableFactura")
        self.tableFactura.setRowCount(0)
        self.tableFactura.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableFactura.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableFactura.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableFactura.verticalHeader().setVisible(False)
        #ancho de las columnas
        self.tableFactura.setColumnWidth(0,100)
        self.tableFactura.setColumnWidth(1,124)
        self.tableFactura.setColumnWidth(2,350)

        #cabecera de la tabla

        self.tableFactura.setColumnHidden(0,True)

        self.tablas.headerBuscarFactura(0, self.tableFactura)    
        self.tablas.headerBuscarFactura(1, self.tableFactura)    
        self.tablas.headerBuscarFactura(2, self.tableFactura)   
        self.gridLayout.addWidget(self.tableFactura, 0, 0, 1, 1)

        self.retranslateUi(ventanaBuscarFactura)
        QtCore.QMetaObject.connectSlotsByName(ventanaBuscarFactura)

        #todos los eventos de la ventana
        self.editFactura.textChanged.connect(self.llenadoTabla)
        self.tableFactura.clicked.connect(self.habilitarBoton)
        self.tableFactura.doubleClicked.connect(lambda:self.facturaSeleccionada(ventanaBuscarFactura))
        self.buttonAceptar.clicked.connect(lambda:self.facturaSeleccionada(ventanaBuscarFactura))
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaBuscarFactura))

    def retranslateUi(self, ventanaBuscarFactura):
        _translate = QtCore.QCoreApplication.translate
        ventanaBuscarFactura.setWindowTitle(_translate("ventanaBuscarFactura", "Buscar Factura"))
        self.buttonAceptar.setText(_translate("ventanaBuscarFactura", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaBuscarFactura", "Cancelar"))


        self.llenadoTabla()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaBuscarFactura = QtWidgets.QDialog()
    ui = Ui_VentanaBuscarFactura()
    ui.setupUi(ventanaBuscarFactura)
    ventanaBuscarFactura.show()
    sys.exit(app.exec())
