# Form implementation generated from reading ui file 'buscarcliente.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaBuscarCliente(object):
    def setupUi(self, ventanaBuscarCliente):
        ventanaBuscarCliente.setObjectName("ventanaBuscarCliente")
        ventanaBuscarCliente.resize(480, 480) 
        ventanaBuscarCliente.setMinimumSize(QtCore.QSize(480, 480))
        ventanaBuscarCliente.setMaximumSize(QtCore.QSize(480, 480))

        #########pocisionar ventana centrada#####
        qr = ventanaBuscarCliente.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaBuscarCliente.move(qr.topLeft())
        #######################################

        ventanaBuscarCliente.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/User group.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaBuscarCliente.setWindowIcon(icon)
        self.groupBox_3 = QtWidgets.QGroupBox(ventanaBuscarCliente)
        self.groupBox_3.setGeometry(QtCore.QRect(1, 430, 478, 48))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonAceptar.setGeometry(QtCore.QRect(130, 11, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonAceptar.setEnabled(False)
        self.buttonCancelar.setGeometry(QtCore.QRect(290, 11, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.groupBox = QtWidgets.QGroupBox(ventanaBuscarCliente)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 478, 50))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.editCliente = QtWidgets.QLineEdit(self.groupBox)
        self.editCliente.setGeometry(QtCore.QRect(10, 16, 460, 22))
        self.editCliente.setObjectName("editCliente")
        self.groupBox_2 = QtWidgets.QGroupBox(ventanaBuscarCliente)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 50, 478, 380))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1, 5, 476, 374))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableCliente = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableCliente.setColumnCount(2)
        self.tableCliente.setObjectName("tableCliente")
        self.tableCliente.setRowCount(0)
        self.tableCliente.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableCliente.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableCliente.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableCliente.verticalHeader().setVisible(False)
        #ancho de las columnas
        self.tableCliente.setColumnWidth(0,124)
        self.tableCliente.setColumnWidth(1,350)

        #cabecera de la tabla

        self.tablas.headerBuscarCliente(0, self.tableCliente)    
        self.tablas.headerBuscarCliente(1, self.tableCliente)   

        self.gridLayout.addWidget(self.tableCliente, 0, 0, 1, 1)

        self.retranslateUi(ventanaBuscarCliente)
        QtCore.QMetaObject.connectSlotsByName(ventanaBuscarCliente)

        #todos los eventos de la ventana
        self.editCliente.textChanged.connect(self.llenadoTabla)
        self.tableCliente.clicked.connect(self.habilitarBoton)
        self.tableCliente.doubleClicked.connect(lambda:self.clienteSeleccionado(ventanaBuscarCliente))
        self.buttonAceptar.clicked.connect(lambda:self.clienteSeleccionado(ventanaBuscarCliente))
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaBuscarCliente))

    def retranslateUi(self, ventanaBuscarCliente):
        _translate = QtCore.QCoreApplication.translate
        ventanaBuscarCliente.setWindowTitle(_translate("ventanaBuscarCliente", "Buscar Cliente"))
        self.buttonAceptar.setText(_translate("ventanaBuscarCliente", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaBuscarCliente", "Cancelar"))


        self.llenadoTabla()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaBuscarCliente = QtWidgets.QDialog()
    ui = Ui_VentanaBuscarCliente()
    ui.setupUi(ventanaBuscarCliente)
    ventanaBuscarCliente.show()
    sys.exit(app.exec())
