# Form implementation generated from reading ui file 'QtForm/cliente.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaCliente(object):
    def setupUi(self, ventanaCliente):
        ventanaCliente.setObjectName("ventanaCliente")
        ventanaCliente.resize(433, 422)
        ventanaCliente.setMinimumSize(QtCore.QSize(433, 422))
        ventanaCliente.setMaximumSize(QtCore.QSize(433, 422))

        #########pocisionar ventana centrada#####
        qr = ventanaCliente.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaCliente.move(qr.topLeft())
        #######################################

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("QtForm/../img/User group.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaCliente.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaCliente)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 431, 175))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 25, 67, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(64, 64, 81, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 104, 131, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(80, 143, 67, 19))
        self.label_4.setObjectName("label_4")
        self.editCliente = QtWidgets.QLineEdit(self.groupBox)
        self.editCliente.setGeometry(QtCore.QRect(145, 20, 270, 27))
        self.editCliente.setObjectName("editCliente")
        self.editDireccion = QtWidgets.QLineEdit(self.groupBox)
        self.editDireccion.setGeometry(QtCore.QRect(145, 60, 270, 27))
        self.editDireccion.setObjectName("editDireccion")
        self.editContrato = QtWidgets.QLineEdit(self.groupBox)
        self.editContrato.setGeometry(QtCore.QRect(145, 100, 270, 27))
        self.editContrato.setObjectName("editContrato")
        self.editCuenta = QtWidgets.QLineEdit(self.groupBox)
        self.editCuenta.setGeometry(QtCore.QRect(145, 140, 270, 27))
        self.editCuenta.setObjectName("editCuenta")
        ###### Valido solo numeros y 16 digitos de las cuentas
        self.editCuenta.setValidator(QtGui.QRegularExpressionValidator(QtCore.QRegularExpression("[0-9]*")))
        self.editCuenta.setMaxLength(16)
        ###################################################
        self.groupBox_3 = QtWidgets.QGroupBox(ventanaCliente)
        self.groupBox_3.setGeometry(QtCore.QRect(1, 211, 431, 210))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_2 = QtWidgets.QGroupBox(ventanaCliente)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 173, 431, 36))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolBar = QtWidgets.QToolBar(self.groupBox_2)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/save.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/03.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/04.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/21.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/printer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)

        self.actionSave = QtGui.QAction(self)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionAdd = QtGui.QAction(self)
        self.actionAdd.setIcon(icon2)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtGui.QAction(self)
        self.actionDelete.setIcon(icon3)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEdit = QtGui.QAction(self)
        self.actionEdit.setIcon(icon4)
        self.actionEdit.setObjectName("actionEdit")
        self.actionPrint = QtGui.QAction(self)
        self.actionPrint.setIcon(icon5)
        self.actionPrint.setObjectName("actionPrint")

        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 431, 210))
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)        
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.verticalHeader().setVisible(False)

        #ancho de las columnas
        self.tableWidget.setColumnWidth(0,80)
        self.tableWidget.setColumnWidth(1,228)
        self.tableWidget.setColumnWidth(2,100)
        self.tableWidget.setColumnWidth(3,100) 
        self.tableWidget.setColumnWidth(4,100)
        self.tableWidget.setColumnWidth(5,100)
        self.tableWidget.setColumnWidth(6,100)
        self.tableWidget.setColumnWidth(7,100)

        self.tableWidget.setColumnHidden(0,True)
        self.tableWidget.setColumnHidden(4,True)
        self.tableWidget.setColumnHidden(5,True)
        self.tableWidget.setColumnHidden(6,True)
        self.tableWidget.setColumnHidden(7,True)
        #cabecera de la tabla
     
        self.tablas.headerFichaClientes(0, self.tableWidget)    
        self.tablas.headerFichaClientes(1, self.tableWidget)    
        self.tablas.headerFichaClientes(2, self.tableWidget)    
        self.tablas.headerFichaClientes(3, self.tableWidget)   
        self.tablas.headerFichaClientes(4, self.tableWidget)   
        self.tablas.headerFichaClientes(5, self.tableWidget)  
        self.tablas.headerFichaClientes(6, self.tableWidget)   
        self.tablas.headerFichaClientes(7, self.tableWidget)      
        self.groupBox.raise_()
        self.groupBox_3.raise_()


        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(ventanaCliente) 
        QtCore.QMetaObject.connectSlotsByName(ventanaCliente)

        #todos los eventos de la ventana
        self.actionAdd.triggered.connect(self.nuevaFichaCliente)
        self.actionSave.triggered.connect(self.guardarCliente)
        self.actionDelete.triggered.connect(self.eliminarFichaCliente)
        self.actionEdit.triggered.connect(self.editarFichaCliente)
        self.tableWidget.doubleClicked.connect(self.editarFichaCliente)
        self.tableWidget.clicked.connect(self.fichaClienteSeleccionada)

        self.editCliente.textChanged.connect(self.verificarCampos)
        self.editContrato.textChanged.connect(self.verificarCampos)
        self.editCuenta.textChanged.connect(self.verificarCampos)
        self.editDireccion.textChanged.connect(self.verificarCampos)

    def retranslateUi(self, ventanaCliente):
        _translate = QtCore.QCoreApplication.translate
        ventanaCliente.setWindowTitle(_translate("ventanaCliente", "Insertar Cliente"))
        self.label.setText(_translate("ventanaCliente", "Cliente:"))
        self.label_2.setText(_translate("ventanaCliente", "Dirección:"))
        self.label_3.setText(_translate("ventanaCliente", "Número Contrato:"))
        self.label_4.setText(_translate("ventanaCliente", "Cuenta:"))
        self.actionAdd.setText(_translate("ventanaCliente", "Agregar Ficha de Cliente"))
        self.actionSave.setText(_translate("ventanaCliente", "Guardar Cliente"))
        self.actionDelete.setText(_translate("ventanaCliente", "Eliminar Ficha de Cliente"))
        self.actionEdit.setText(_translate("ventanaCliente", "Editar Ficha de Cliente"))
        self.actionPrint.setText(_translate("ventanaCliente", "Imprimir lista de Fichas de Clientes"))
        
        self.inicializarVentana(ventanaCliente)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaCliente = QtWidgets.QDialog()
    ui = Ui_VentanaCliente()
    ui.setupUi(ventanaCliente)
    ventanaCliente.show()
    sys.exit(app.exec())