# Form implementation generated from reading ui file 'QtForm/cobro.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from entidades.entCobroFactura import eCobroFactura
from funciones.misObjetos import QComboReturn
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaCobro(object):
    def setupUi(self, ventanaCobro):
        ventanaCobro.setObjectName("ventanaCobro")
        ventanaCobro.resize(791, 584)
        ventanaCobro.setMinimumSize(QtCore.QSize(791, 584))
        ventanaCobro.setMaximumSize(QtCore.QSize(791, 584))

        #########pocisionar ventana centrada#####
        qr = ventanaCobro.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaCobro.move(qr.topLeft())
        #######################################

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Dollar.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaCobro.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaCobro)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 789, 582))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 24, 67, 19))
        self.label.setObjectName("label")
        self.labelCliente = QtWidgets.QLabel(self.groupBox)
        self.labelCliente.setGeometry(QtCore.QRect(40, 60, 531, 19))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCliente.setFont(font)
        self.labelCliente.setObjectName("labelCliente")
        self.labelCliente.setVisible(True)
        self.editCliente = QtWidgets.QLineEdit(self.groupBox)
        self.editCliente.setGeometry(QtCore.QRect(100, 22, 250, 27))
        self.editCliente.setObjectName("editCliente")
        self.buttonCliente = QtWidgets.QToolButton(self.editCliente)
        self.buttonCliente.setGeometry(QtCore.QRect(222, 0, 27, 26))
        self.buttonCliente.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.buttonCliente.setObjectName("buttonCliente")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(617, 24, 111, 19))
        self.label_2.setObjectName("label_2")
        self.editFecha = QtWidgets.QLineEdit(self.groupBox)
        self.editFecha.setEnabled(False)
        self.editFecha.setGeometry(QtCore.QRect(670, 22, 113, 27))
        self.editFecha.setObjectName("editFecha")
        self.editCobro = QtWidgets.QLineEdit(self.groupBox)
        self.editCobro.setEnabled(False)
        self.editCobro.setGeometry(QtCore.QRect(670, 58, 113, 27))
        self.editCobro.setObjectName("editCobro")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(590, 60, 111, 19))
        self.label_3.setObjectName("label_3")
        self.tableCobro = QtWidgets.QTableWidget(self.groupBox)
        self.tableCobro.setGeometry(QtCore.QRect(1, 195, 787, 364))
        self.tableCobro.setColumnCount(5)
        self.tableCobro.setObjectName("tableCobro")
        self.tableCobro.setRowCount(0)
        self.tableCobro.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tableCobro.customContextMenuRequested.connect(self.contexMenuEvent)

        #ancho de las columnas
        self.tableCobro.setColumnWidth(0,10)
        self.tableCobro.setColumnWidth(1,260)
        self.tableCobro.setColumnWidth(2,260)
        self.tableCobro.setColumnWidth(3,265)
        self.tableCobro.setColumnWidth(4,150)

        self.tableCobro.setColumnHidden(0, True)
        self.tableCobro.setColumnHidden(4, True)
        #cabecera de la tabla
        self.headerTablaCobro()


        self.tableCobro.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 94, 160, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(564, 94, 91, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(505, 126, 120, 19))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(63, 126, 141, 19))
        self.label_7.setObjectName("label_7")
        self.labelTotal = QtWidgets.QLabel(self.groupBox)
        self.labelTotal.setGeometry(QtCore.QRect(660, 561, 120, 19))
        self.labelTotal.setObjectName("labelTotal")
        self.labelTotal.setVisible(False)
        self.editNumero = QtWidgets.QLineEdit(self.groupBox)
        self.editNumero.setGeometry(QtCore.QRect(629, 90, 154, 27))
        self.editNumero.setObjectName("editNumero")

        self.dateFechaEmision = QtWidgets.QDateEdit(self.groupBox)
        self.dateFechaEmision.setGeometry(QtCore.QRect(190, 122, 220, 28))
        self.dateFechaEmision.setDisplayFormat('dd/MM/yyyy')
        self.dateFechaEmision.setCalendarPopup(True)
        self.dateFechaEmision.setObjectName("dateFechaEmision")
        self.editTotalPago = QtWidgets.QLineEdit(self.groupBox)
        self.editTotalPago.setGeometry(QtCore.QRect(629, 123, 154, 27))
        self.editTotalPago.setObjectName("editTotalPago")
        self.editTotalPago.setValidator(QtGui.QRegularExpressionValidator(QtCore.QRegularExpression("^[0-9]*\.?[0-9]{1,2}")))
        self.comboPago = QComboReturn(self.groupBox)
        self.comboPago.setGeometry(QtCore.QRect(190, 90, 220, 27))
        self.comboPago.setObjectName("comboPago")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 155, 787, 37))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolBar = QtWidgets.QToolBar(self.groupBox_2)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/03.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/04.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/save.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/printer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)

        self.actionAdd = QtGui.QAction(self)
        self.actionAdd.setIcon(icon1)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtGui.QAction(self)
        self.actionDelete.setIcon(icon2)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSave = QtGui.QAction(self)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtGui.QAction(self)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")


        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(ventanaCobro)
        QtCore.QMetaObject.connectSlotsByName(ventanaCobro)

        #todos los eventos de la ventana
        self.buttonCliente.clicked.connect(self.verificarCliente)
        self.editCliente.returnPressed.connect(self.verificarCliente)
        self.comboPago.returnPressed.connect(self.editNumero.setFocus)
        self.editNumero.returnPressed.connect(self.editTotalPago.setFocus) 
        self.editTotalPago.returnPressed.connect(self.iniciarTablaCobro)
        self.comboPago.currentTextChanged.connect(self.verificarDatos)
        self.editNumero.textChanged.connect((self.verificarDatos)) 
        self.editTotalPago.textChanged.connect((self.verificarDatos))
        self.actionAdd.triggered.connect(self.iniciarTablaCobro)
        self.actionSave.triggered.connect(self.guardarCobro)
        self.actionDelete.triggered.connect(self.eliminarCobro)
        self.actionPrint.triggered.connect(self.vistaPrevia)


    def retranslateUi(self, ventanaCobro):
        _translate = QtCore.QCoreApplication.translate
        ventanaCobro.setWindowTitle(_translate("ventanaCobro", "Cobro"))
        self.label.setText(_translate("ventanaCobro", "Cliente:"))
        self.labelCliente.setText(_translate("ventanaCobro", "Nombre del cliente para hacer la recepcion"))
        self.buttonCliente.setText(_translate("ventanaCobro", "..."))
        self.label_2.setText(_translate("ventanaCobro", "Fecha:"))
        self.label_3.setText(_translate("ventanaCobro", "No. Cobro:"))
        self.label_4.setText(_translate("ventanaCobro", "Instrumento de Pago:"))
        self.label_5.setText(_translate("ventanaCobro", "Número:"))
        self.label_6.setText(_translate("ventanaCobro", "Importe del Pago:"))
        self.label_7.setText(_translate("ventanaCobro", "Fecha de Emisión:"))
        self.labelTotal.setText(_translate("ventanaCobro", "0.00"))
        self.actionAdd.setText(_translate("ventanaCobro", "Adicionar fila"))
        self.actionDelete.setText(_translate("ventanaCobro", "Eliminar Fila"))
        self.actionSave.setText(_translate("ventanaCobro", "Guardar Cobro"))
        self.actionPrint.setText(_translate("ventanaCobro", "Imprimir Cobro"))


        self.inicializacionVentana(ventanaCobro)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaCobro = QtWidgets.QDialog()
    ui = Ui_VentanaCobro()
    ui.setupUi(ventanaCobro)
    ventanaCobro.show()
    sys.exit(app.exec())
