# Form implementation generated from reading ui file 'QtForm/devolucion.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaDevolucion(object):
    def setupUi(self, ventanaDevolucion):
        ventanaDevolucion.setObjectName("ventanaDevolucion")
        ventanaDevolucion.resize(555, 250)
        ventanaDevolucion.setMinimumSize(QtCore.QSize(555, 250))
        ventanaDevolucion.setMaximumSize(QtCore.QSize(555, 250))

        #########pocisionar ventana centrada#####
        qr = ventanaDevolucion.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaDevolucion.move(qr.topLeft())
        #######################################

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Devolver.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaDevolucion.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaDevolucion)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 553, 248))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.labelCliente = QtWidgets.QLabel(self.groupBox)
        self.labelCliente.setGeometry(QtCore.QRect(20, 70, 531, 19))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCliente.setFont(font)
        self.labelCliente.setObjectName("labelCliente")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(370, 24, 111, 19))
        self.label_2.setObjectName("label_2")
        self.editFecha = QtWidgets.QLineEdit(self.groupBox)
        self.editFecha.setEnabled(False)
        self.editFecha.setGeometry(QtCore.QRect(423, 22, 113, 27))
        self.editFecha.setObjectName("editFecha")
        self.editDocumento = QtWidgets.QLineEdit(self.groupBox)
        self.editDocumento.setEnabled(False)
        self.editDocumento.setGeometry(QtCore.QRect(137, 22, 113, 27))
        self.editDocumento.setObjectName("editDocumento")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 24, 130, 19))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 114, 91, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(263, 113, 130, 19))
        self.label_6.setObjectName("label_6")
        self.editNumero = QtWidgets.QLineEdit(self.groupBox)
        self.editNumero.setGeometry(QtCore.QRect(85, 110, 150, 27))
        self.editNumero.setObjectName("editNumero")
        self.editMonto = QtWidgets.QLineEdit(self.groupBox)
        self.editMonto.setGeometry(QtCore.QRect(387, 110, 150, 27))
        self.editMonto.setObjectName("editMonto")
        self.editMonto.setValidator(QtGui.QRegularExpressionValidator(QtCore.QRegularExpression("^[0-9]*\.?[0-9]{1,2}")))
        self.dateFechaEmision = QtWidgets.QDateEdit(self.groupBox)
        self.dateFechaEmision.setGeometry(QtCore.QRect(260, 161, 150, 28))
        self.dateFechaEmision.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.dateFechaEmision.setCalendarPopup(True)
        self.dateFechaEmision.setObjectName("dateFechaEmision")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(129, 166, 141, 19))
        self.label_7.setObjectName("label_7")
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(150, 210, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(320, 210, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaDevolucion)
        QtCore.QMetaObject.connectSlotsByName(ventanaDevolucion)

        self.buttonAceptar.clicked.connect(lambda:self.guardarDevolucion(ventanaDevolucion))
        self.buttonCancelar.clicked.connect(lambda:self.cerrarVentana(ventanaDevolucion))

    def retranslateUi(self, ventanaDevolucion):
        _translate = QtCore.QCoreApplication.translate
        ventanaDevolucion.setWindowTitle(_translate("ventanaDevolucion", "Devolución"))
        self.labelCliente.setText(_translate("ventanaDevolucion", "Nombre del cliente para hacer la recepcion"))
        self.label_2.setText(_translate("ventanaDevolucion", "Fecha:"))
        self.label_3.setText(_translate("ventanaDevolucion", "No. Documento:"))
        self.label_5.setText(_translate("ventanaDevolucion", "Número:"))
        self.label_6.setText(_translate("ventanaDevolucion", "Monto a devolver:"))
        self.dateFechaEmision.setDisplayFormat(_translate("ventanaDevolucion", "dd/MM/yyyy"))
        self.label_7.setText(_translate("ventanaDevolucion", "Fecha de Emisión:"))
        self.buttonAceptar.setText(_translate("ventanaDevolucion", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaDevolucion", "Cancelar"))

        self.inicializarVentana(ventanaDevolucion)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaDevolucion = QtWidgets.QDialog()
    ui = Ui_VentanaDevolucion()
    ui.setupUi(ventanaDevolucion)
    ventanaDevolucion.show()
    sys.exit(app.exec())
