# Form implementation generated from reading ui file 'QtForm/eliminar.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaEliminar(object): 
    def setupUi(self, ventanaEliminar):
        ventanaEliminar.setObjectName("ventanaEliminar")
        ventanaEliminar.resize(480, 183)
        ventanaEliminar.setMinimumSize(QtCore.QSize(480, 183))
        ventanaEliminar.setMaximumSize(QtCore.QSize(480, 183))
        ventanaEliminar.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)

        #########pocisionar ventana centrada#####
        qr = ventanaEliminar.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaEliminar.move(qr.topLeft())
        #######################################

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/information.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaEliminar.setWindowIcon(icon)
        self.groupBox_2 = QtWidgets.QGroupBox(ventanaEliminar)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 1, 478, 181))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonCancelar.setGeometry(QtCore.QRect(280, 143, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon1)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonAceptar.setGeometry(QtCore.QRect(120, 143, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon2)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 100, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.generales.resource_path("../img/About.png")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.labelTexto = QtWidgets.QLabel(self.groupBox_2)
        self.labelTexto.setGeometry(QtCore.QRect(130, 30, 330, 90))
        self.labelTexto.setObjectName("labelTexto")

        self.retranslateUi(ventanaEliminar)
        QtCore.QMetaObject.connectSlotsByName(ventanaEliminar)

        self.buttonAceptar.clicked.connect(lambda:self.respuestaVentana(1, ventanaEliminar))
        self.buttonCancelar.clicked.connect(lambda:self.respuestaVentana(0, ventanaEliminar))

    def retranslateUi(self, ventanaEliminar):
        _translate = QtCore.QCoreApplication.translate
        ventanaEliminar.setWindowTitle(_translate("ventanaEliminar", "Eliminar"))
        self.buttonCancelar.setText(_translate("ventanaEliminar", "Cancelar"))
        self.buttonAceptar.setText(_translate("ventanaEliminar", "Aceptar"))
        self.labelTexto.setText(_translate("ventanaEliminar", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaEliminar = QtWidgets.QDialog()
    ui = Ui_VentanaEliminar()
    ui.setupUi(ventanaEliminar)
    ventanaEliminar.show()
    sys.exit(app.exec())
