# Form implementation generated from reading ui file 'QtForm/fecha.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from ctypes import alignment
from turtle import left
from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_ventanaFechaProcesamiento(object):
    def setupUi(self, ventanaFechaProcesamiento):
        ventanaFechaProcesamiento.setObjectName("ventanaFechaProcesamiento")
        ventanaFechaProcesamiento.resize(470, 207)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaFechaProcesamiento.sizePolicy().hasHeightForWidth())
        ventanaFechaProcesamiento.setSizePolicy(sizePolicy)
        ventanaFechaProcesamiento.setMinimumSize(QtCore.QSize(470, 207))
        ventanaFechaProcesamiento.setMaximumSize(QtCore.QSize(470, 207))

        #########pocisionar ventana centrada#####
        qr = ventanaFechaProcesamiento.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaFechaProcesamiento.move(qr.topLeft())
        #######################################


        ventanaFechaProcesamiento.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu) 
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/cambiofecha.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaFechaProcesamiento.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaFechaProcesamiento)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 468, 205))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        
        self.dateProcesamiento = QtWidgets.QDateEdit(self.groupBox)
        self.dateProcesamiento.setGeometry(QtCore.QRect(50, 50, 371, 28))
        self.dateProcesamiento.setDisplayFormat('dd/MM/yyyy')
        self.dateProcesamiento.setCalendarPopup(True)
        self.dateProcesamiento.setObjectName("dateProcesamiento")
        
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(120, 130, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(270, 130, 88, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancelar.sizePolicy().hasHeightForWidth())
        self.buttonCancelar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaFechaProcesamiento)
        QtCore.QMetaObject.connectSlotsByName(ventanaFechaProcesamiento)
        
        
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaFechaProcesamiento))
        self.buttonAceptar.clicked.connect(lambda:self.guardarFechaProcesamiento(ventanaFechaProcesamiento))
        

    def retranslateUi(self, ventanaFechaProcesamiento):
        _translate = QtCore.QCoreApplication.translate
        ventanaFechaProcesamiento.setWindowTitle(_translate("ventanaFechaProcesamiento", "Fecha de Procesamiento"))
        self.buttonAceptar.setText(_translate("ventanaFechaProcesamiento", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaFechaProcesamiento", "Cancelar"))
        
        self.inicializacionVentana()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaFechaProcesamiento = QtWidgets.QDialog()
    ui = Ui_ventanaFechaProcesamiento()
    ui.setupUi(ventanaFechaProcesamiento)
    ventanaFechaProcesamiento.show()
    sys.exit(app.exec())
    
