# Form implementation generated from reading ui file 'iniciosession.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaInicioSession(object):
    def setupUi(self, ventanaInicioSession):
        ventanaInicioSession.setObjectName("ventanaInicioSession")
        ventanaInicioSession.resize(353, 233)

        #########pocisionar ventana centrada#####
        qr = ventanaInicioSession.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaInicioSession.move(qr.topLeft())
        #######################################
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaInicioSession.sizePolicy().hasHeightForWidth())
        ventanaInicioSession.setSizePolicy(sizePolicy)
        ventanaInicioSession.setMinimumSize(QtCore.QSize(353, 233))
        ventanaInicioSession.setMaximumSize(QtCore.QSize(353, 233))
        ventanaInicioSession.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Icon.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaInicioSession.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaInicioSession)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 351, 231))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.labelUser = QtWidgets.QLabel(self.groupBox)
        self.labelUser.setGeometry(QtCore.QRect(55, 60, 67, 19))
        self.labelUser.setObjectName("labelUser")
        self.labelPass = QtWidgets.QLabel(self.groupBox)
        self.labelPass.setGeometry(QtCore.QRect(30, 120, 91, 19))
        self.labelPass.setObjectName("labelPass")
        self.editUsuario = QtWidgets.QLineEdit(self.groupBox)
        self.editUsuario.setGeometry(QtCore.QRect(120, 58, 211, 27))
        self.editUsuario.setObjectName("editUsuario")
        self.editPass = QtWidgets.QLineEdit(self.groupBox)
        self.editPass.setGeometry(QtCore.QRect(120, 117, 211, 27))
        self.editPass.setObjectName("editPass")
        self.editPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(80, 180, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(200, 180, 88, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancelar.sizePolicy().hasHeightForWidth())
        self.buttonCancelar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaInicioSession)
        QtCore.QMetaObject.connectSlotsByName(ventanaInicioSession)

        self.buttonAceptar.clicked.connect(lambda:self.inicioSession(ventanaInicioSession))
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarAplicacion(QtWidgets))
        self.editUsuario.returnPressed.connect(self.editPass.setFocus)
        self.editPass.returnPressed.connect(lambda:self.inicioSession(ventanaInicioSession))

    def retranslateUi(self, ventanaInicioSession):
        _translate = QtCore.QCoreApplication.translate
        ventanaInicioSession.setWindowTitle(_translate("ventanaInicioSession", "Inicio de Sessión"))
        self.labelUser.setText(_translate("ventanaInicioSession", "Usuario:"))
        self.labelPass.setText(_translate("ventanaInicioSession", "Contraseña:"))
        self.buttonAceptar.setText(_translate("ventanaInicioSession", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaInicioSession", "Cancelar"))

        #self.editUsuario.setText('aglez')
        #self.editPass.setText('Pepe123++')
        #self.editUsuario.setText('admin')
        #self.editPass.setText('Admin')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaInicioSession = QtWidgets.QDialog()
    ui = Ui_ventanaInicioSession()
    ui.setupUi(ventanaInicioSession)
    ventanaInicioSession.show()
    sys.exit(app.exec())
