# Form implementation generated from reading ui file 'QtForm/notafactura.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaNotaFactura(object):
    def setupUi(self, ventanaNotaFactura):
        ventanaNotaFactura.setObjectName("ventanaNotaFactura")
        ventanaNotaFactura.resize(582, 242)
        ventanaNotaFactura.setMinimumSize(QtCore.QSize(582, 242))
        ventanaNotaFactura.setMaximumSize(QtCore.QSize(582, 242))

        #########pocisionar ventana centrada#####
        qr = ventanaNotaFactura.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaNotaFactura.move(qr.topLeft())
        #######################################
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/nota.jpg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaNotaFactura.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaNotaFactura)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 580, 240))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.textEditNota = QtWidgets.QPlainTextEdit(self.groupBox)
        self.textEditNota.setGeometry(QtCore.QRect(1, 4, 579, 186))
        self.textEditNota.setObjectName("textEditNota")
        
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(160, 200, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(340, 200, 88, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancelar.sizePolicy().hasHeightForWidth())
        self.buttonCancelar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaNotaFactura)
        QtCore.QMetaObject.connectSlotsByName(ventanaNotaFactura)
        
        
        self.buttonAceptar.clicked.connect(lambda:self.guardarNota(ventanaNotaFactura))
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaNotaFactura))

    def retranslateUi(self, ventanaNotaFactura):
        _translate = QtCore.QCoreApplication.translate
        ventanaNotaFactura.setWindowTitle(_translate("ventanaNotaFactura", "Nota de Factura"))
        self.buttonAceptar.setText(_translate("ventanaNotaFactura", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaNotaFactura", "Cancelar"))
        
        self.inicializarVentana()
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)      
    ventanaNotaFactura = QtWidgets.QDialog()
    ui = Ui_VentanaNotaFactura()
    ui.setupUi(ventanaNotaFactura)
    ventanaNotaFactura.show()
    sys.exit(app.exec())
