# Form implementation generated from reading ui file 'reparacion.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_VentanaReparacion(object):
    def setupUi(self, ventanaReparacion):
        ventanaReparacion.setObjectName("ventanaReparacion")
        ventanaReparacion.resize(372, 182)
        ventanaReparacion.setMinimumSize(QtCore.QSize(372, 182))
        ventanaReparacion.setMaximumSize(QtCore.QSize(372, 182))

        #########pocisionar ventana centrada#####
        qr = ventanaReparacion.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaReparacion.move(qr.topLeft())
        #######################################
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/computer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaReparacion.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaReparacion)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 370, 180))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(18, 38, 91, 19))
        self.label.setObjectName("label")
        self.editDescripcion = QtWidgets.QLineEdit(self.groupBox)
        self.editDescripcion.setGeometry(QtCore.QRect(105, 35, 240, 27))
        self.editDescripcion.setObjectName("editDescripcion")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(97, 85, 240, 27))
        self.checkBox.setText("Permitir recepciones multiples")
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("CheckBox")
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(97, 131, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonAceptar.setEnabled(False)
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(227, 131, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaReparacion)
        QtCore.QMetaObject.connectSlotsByName(ventanaReparacion)

        #eventos de la ventana
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaReparacion))
        self.buttonAceptar.clicked.connect(lambda:self.guardarEquipo(ventanaReparacion))
        self.editDescripcion.textChanged.connect(self.verificarCampos)
        self.checkBox.clicked.connect(self.verificarCampos)

    def retranslateUi(self, ventanaReparacion):
        _translate = QtCore.QCoreApplication.translate
        ventanaReparacion.setWindowTitle(_translate("ventanaReparacion", "Insertar Reparable"))
        self.label.setText(_translate("ventanaReparacion", "Descripción:"))
        self.buttonAceptar.setText(_translate("ventanaReparacion", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaReparacion", "Cancelar"))
 

        self.inicializacionVentana(ventanaReparacion)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaReparacion = QtWidgets.QDialog()
    ui = Ui_VentanaReparacion()
    ui.setupUi(ventanaReparacion)
    ventanaReparacion.show()
    sys.exit(app.exec())
