# Form implementation generated from reading ui file 'recepcion.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from entidades.entInventario import eInventario
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaRecepcion(object):
    def setupUi(self, ventanaRecepcion):
        ventanaRecepcion.setObjectName("ventanaRecepcion")
        ventanaRecepcion.resize(845, 584)
        ventanaRecepcion.setMinimumSize(QtCore.QSize(845, 584))
        ventanaRecepcion.setMaximumSize(QtCore.QSize(845, 584))

        #########pocisionar ventana centrada#####
        qr = ventanaRecepcion.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaRecepcion.move(qr.topLeft())
        #######################################
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Recepcion.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaRecepcion.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaRecepcion)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 843, 582))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 24, 67, 19))
        self.label.setObjectName("label")
        self.labelCliente = QtWidgets.QLabel(self.groupBox)
        self.labelCliente.setGeometry(QtCore.QRect(100, 60, 651, 19))
        self.labelCliente.setVisible(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCliente.setFont(font)
        self.labelCliente.setObjectName("labelCliente")
        self.editCliente = QtWidgets.QLineEdit(self.groupBox)
        self.editCliente.setGeometry(QtCore.QRect(100, 22, 250, 27))
        self.editCliente.setObjectName("editCliente")
        self.buttonCliente = QtWidgets.QToolButton(self.editCliente)
        self.buttonCliente.setGeometry(QtCore.QRect(222, 0, 27, 26))
        self.buttonCliente.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.buttonCliente.setObjectName("buttonCliente")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(667, 24, 111, 19))
        self.label_2.setObjectName("label_2")
        self.editFecha = QtWidgets.QLineEdit(self.groupBox)
        self.editFecha.setEnabled(False)
        self.editFecha.setGeometry(QtCore.QRect(720, 22, 113, 27))
        self.editFecha.setObjectName("editFecha")
        self.editRecepcion = QtWidgets.QLineEdit(self.groupBox)
        self.editRecepcion.setEnabled(False)
        self.editRecepcion.setGeometry(QtCore.QRect(720, 58, 113, 27))
        self.editRecepcion.setObjectName("editRecepcion")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(611, 60, 111, 19))
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 95, 841, 37))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolBar = QtWidgets.QToolBar(self.groupBox_2)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/03.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/04.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/save.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/printer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)

        self.actionAdd = QtGui.QAction(self)
        self.actionAdd.setIcon(icon1)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtGui.QAction(self)
        self.actionDelete.setIcon(icon2)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSave = QtGui.QAction(self)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtGui.QAction(self)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")
        self.tableRecepcion = QtWidgets.QTableWidget(self.groupBox)
        self.tableRecepcion.setGeometry(QtCore.QRect(1, 132, 841, 450))
        self.tableRecepcion.setColumnCount(7)
        self.tableRecepcion.setObjectName("tableRecepcion")
        self.tableRecepcion.setRowCount(0)
        self.tableRecepcion.verticalHeader().setVisible(False)
        self.tableRecepcion.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tableRecepcion.customContextMenuRequested.connect(self.contexMenuEvent)

        #ancho de las columnas
        self.tableRecepcion.setColumnWidth(0,10)
        self.tableRecepcion.setColumnWidth(1,150)
        self.tableRecepcion.setColumnWidth(2,150)
        self.tableRecepcion.setColumnWidth(3,150)
        self.tableRecepcion.setColumnWidth(4,150)
        self.tableRecepcion.setColumnWidth(5,50)
        self.tableRecepcion.setColumnWidth(6,188)

        self.tableRecepcion.setColumnHidden(0, True)
        #cabecera de la tabla
        self.headerTablaRecepcion()


        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(ventanaRecepcion)
        QtCore.QMetaObject.connectSlotsByName(ventanaRecepcion)
        
        # Eventos de la ventana
        einventario = eInventario()
        self.buttonCliente.clicked.connect(self.verificarCliente)
        self.editCliente.returnPressed.connect(self.verificarCliente)    
        self.actionAdd.triggered.connect(lambda:self.lineaTablaInventario(einventario))
        self.actionDelete.triggered.connect(self.eliminarRecepcion)
        self.actionSave.triggered.connect(self.guardarRecepcion)
        self.actionPrint.triggered.connect(self.vistaPrevia)


    def retranslateUi(self, ventanaRecepcion):
        _translate = QtCore.QCoreApplication.translate
        ventanaRecepcion.setWindowTitle(_translate("ventanaRecepcion", "Recepción"))
        self.label.setText(_translate("ventanaRecepcion", "Cliente:"))
        self.labelCliente.setText(_translate("ventanaRecepcion", "Nombre del cliente para hacer la recepcion"))
        self.buttonCliente.setText(_translate("ventanaRecepcion", "..."))
        self.label_2.setText(_translate("ventanaRecepcion", "Fecha:"))
        self.label_3.setText(_translate("ventanaRecepcion", "No. Recepción:"))
        self.actionAdd.setText(_translate("ventanaRecepcion", "Adicionar Fila"))
        self.actionDelete.setText(_translate("ventanaRecepcion", "Eliminar Fila"))
        self.actionSave.setText(_translate("ventanaRecepcion", "Guardar Recepción"))
        self.actionPrint.setText(_translate("ventanaRecepcion", "Imprimir Recepción"))

    
        self.inicializacionVentana(ventanaRecepcion)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaRecepcion = QtWidgets.QDialog()
    ui = Ui_VentanaRecepcion()
    ui.setupUi(ventanaRecepcion)
    ventanaRecepcion.show()
    sys.exit(app.exec())
