# Form implementation generated from reading ui file 'QtForm/usuario.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaUsuario(object):
    def setupUi(self, ventanaUsuario): 
        ventanaUsuario.setObjectName("ventanaUsuario")
        ventanaUsuario.resize(433, 322)
        ventanaUsuario.setMinimumSize(QtCore.QSize(433, 322))
        ventanaUsuario.setMaximumSize(QtCore.QSize(433, 322))

        #########pocisionar ventana centrada#####
        qr = ventanaUsuario.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaUsuario.move(qr.topLeft())
        #######################################
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Useradmin.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaUsuario.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaUsuario)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 431, 320))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(18, 25, 139, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(71, 64, 90, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(19, 104, 140, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(91, 143, 67, 19))
        self.label_4.setObjectName("label_4")
        self.editUsername = QtWidgets.QLineEdit(self.groupBox)
        self.editUsername.setGeometry(QtCore.QRect(156, 20, 256, 27))
        self.editUsername.setObjectName("editUsername")
        self.editUsername.setValidator(QtGui.QRegularExpressionValidator(QtCore.QRegularExpression("^[a-z0-9.-_]*")))
        self.editPasswd = QtWidgets.QLineEdit(self.groupBox)
        self.editPasswd.setGeometry(QtCore.QRect(156, 60, 256, 27))
        self.editPasswd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.editPasswd.setObjectName("editPasswd")
        self.editReptPasswd = QtWidgets.QLineEdit(self.groupBox)
        self.editReptPasswd.setGeometry(QtCore.QRect(156, 100, 256, 27))
        self.editReptPasswd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.editReptPasswd.setObjectName("editReptPasswd")
        self.editNombre = QtWidgets.QLineEdit(self.groupBox)
        self.editNombre.setGeometry(QtCore.QRect(156, 140, 256, 27))
        self.editNombre.setObjectName("editNombre")
        self.editApellidos = QtWidgets.QLineEdit(self.groupBox)
        self.editApellidos.setGeometry(QtCore.QRect(156, 180, 256, 27))
        self.editApellidos.setObjectName("editApellidos")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(86, 183, 74, 19))
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(17, 220, 145, 19))
        self.label_6.setObjectName("label_6")
        self.editCarnet = QtWidgets.QLineEdit(self.groupBox)
        self.editCarnet.setGeometry(QtCore.QRect(156, 220, 256, 27))
        self.editCarnet.setMaxLength(11)
        self.editCarnet.setObjectName("editCarnet")
        ###### Valido solo numeros y 11 digitos del carnet
        self.editCarnet.setValidator(QtGui.QRegularExpressionValidator(QtCore.QRegularExpression("[0-9]*")))
        self.editCarnet.setMaxLength(11)
        ###################################################
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(120, 278, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(260, 278, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaUsuario)
        QtCore.QMetaObject.connectSlotsByName(ventanaUsuario)

        ####eventos de la vista
        self.buttonAceptar.clicked.connect(lambda:self.guardarUsuario(ventanaUsuario))
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaUsuario))



    def retranslateUi(self, ventanaUsuario):
        _translate = QtCore.QCoreApplication.translate
        ventanaUsuario.setWindowTitle(_translate("ventanaUsuario", "Insertar Usuario"))
        self.label.setText(_translate("ventanaUsuario", "Nombre de Usuario:"))
        self.label_2.setText(_translate("ventanaUsuario", "Contraseña:"))
        self.label_3.setText(_translate("ventanaUsuario", "Repatir Contraseña:"))
        self.label_4.setText(_translate("ventanaUsuario", "Nombre:"))
        self.label_5.setText(_translate("ventanaUsuario", "Apellidos:"))
        self.label_6.setText(_translate("ventanaUsuario", "Carnet de Identidad:"))
        self.buttonAceptar.setText(_translate("ventanaUsuario", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaUsuario", "Cancelar"))

        self.inicializarVentana(ventanaUsuario)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaUsuario = QtWidgets.QDialog()
    ui = Ui_VentanaUsuario()
    ui.setupUi(ventanaUsuario)
    ventanaUsuario.show()
    sys.exit(app.exec())
