# Form implementation generated from reading ui file 'unidadmedida.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaUnidadMedida(object):
    def setupUi(self, ventanaUnidadMedida):
        ventanaUnidadMedida.setObjectName("ventanaUnidadMedida")
        ventanaUnidadMedida.resize(372, 212)
        ventanaUnidadMedida.setMinimumSize(QtCore.QSize(372, 212))
        ventanaUnidadMedida.setMaximumSize(QtCore.QSize(372, 212))

        #########pocisionar ventana centrada#####
        qr = ventanaUnidadMedida.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaUnidadMedida.move(qr.topLeft())
        #######################################

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/pencil-ruler.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaUnidadMedida.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaUnidadMedida)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 370, 210))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(18, 38, 91, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(56, 96, 71, 19))
        self.label_2.setObjectName("label_2")
        self.editDescripcion = QtWidgets.QLineEdit(self.groupBox)
        self.editDescripcion.setGeometry(QtCore.QRect(105, 35, 240, 27))
        self.editDescripcion.setObjectName("editDescripcion")
        self.editSigla = QtWidgets.QLineEdit(self.groupBox)
        self.editSigla.setGeometry(QtCore.QRect(105, 92, 240, 27))
        self.editSigla.setObjectName("editSigla")
        self.buttonAceptar = QtWidgets.QPushButton(self.groupBox)
        self.buttonAceptar.setGeometry(QtCore.QRect(97, 159, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Ok.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAceptar.setIcon(icon1)
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.buttonAceptar.setEnabled(False)
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(227, 159, 88, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon2)
        self.buttonCancelar.setObjectName("buttonCancelar")

        self.retranslateUi(ventanaUnidadMedida)
        QtCore.QMetaObject.connectSlotsByName(ventanaUnidadMedida)


        #todos los eventos de la ventana
        self.buttonCancelar.clicked.connect(lambda:self.generales.cerrarVentana(ventanaUnidadMedida))
        self.buttonAceptar.clicked.connect(lambda:self.guardarUnidadMedida(ventanaUnidadMedida))
        self.editDescripcion.textChanged.connect(self.verificarCampos)
        self.editSigla.textChanged.connect(self.verificarCampos)

    def retranslateUi(self, ventanaUnidadMedida):
        _translate = QtCore.QCoreApplication.translate
        ventanaUnidadMedida.setWindowTitle(_translate("ventanaUnidadMedida", "Insertar Unidad de Medida"))
        self.label.setText(_translate("ventanaUnidadMedida", "Descripción:"))
        self.label_2.setText(_translate("ventanaUnidadMedida", "Siglas:"))
        self.buttonAceptar.setText(_translate("ventanaUnidadMedida", "Aceptar"))
        self.buttonCancelar.setText(_translate("ventanaUnidadMedida", "Cancelar"))


        self.inicializacionVentana(ventanaUnidadMedida)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaUnidadMedida = QtWidgets.QDialog()
    ui = Ui_VentanaUnidadMedida()
    ui.setupUi(ventanaUnidadMedida)
    ventanaUnidadMedida.show()
    sys.exit(app.exec())
