# Form implementation generated from reading ui file 'QtForm/cargarinventario.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaCargarInventario(object):
    def setupUi(self, ventanaCargarInventario):
        ventanaCargarInventario.setObjectName("ventanaCargarInventario")
        ventanaCargarInventario.resize(442, 302)
        ventanaCargarInventario.setMinimumSize(QtCore.QSize(442, 302))
        ventanaCargarInventario.setMaximumSize(QtCore.QSize(442, 302))

        #########pocisionar ventana centrada#####
        qr = ventanaCargarInventario.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        ventanaCargarInventario.move(qr.topLeft())
        #######################################


        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/inventario.jpeg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaCargarInventario.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(ventanaCargarInventario)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 440, 300))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 50, 67, 19))
        self.label.setObjectName("label")
        self.comboCliente = QtWidgets.QComboBox(self.groupBox)
        self.comboCliente.setGeometry(QtCore.QRect(90, 46, 310, 27))
        self.comboCliente.setObjectName("comboCliente")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 67, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(35, 150, 67, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(26, 200, 67, 19))
        self.label_4.setObjectName("label_4")
        self.buttonImprimir = QtWidgets.QPushButton(self.groupBox)
        self.buttonImprimir.setGeometry(QtCore.QRect(110, 250, 88, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/printer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonImprimir.setIcon(icon)
        self.buttonImprimir.setObjectName("buttonImprimir")
        self.buttonCancelar = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancelar.setGeometry(QtCore.QRect(250, 250, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.generales.resource_path("../img/Cancel.ico")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancelar.setIcon(icon1)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.comboEquipo = QtWidgets.QComboBox(self.groupBox)
        self.comboEquipo.setGeometry(QtCore.QRect(90, 96, 310, 27))
        self.comboEquipo.setObjectName("comboEquipo")
        self.comboMarca = QtWidgets.QComboBox(self.groupBox)
        self.comboMarca.setGeometry(QtCore.QRect(90, 147, 310, 27))
        self.comboMarca.setObjectName("comboMarca")
        self.comboModelo = QtWidgets.QComboBox(self.groupBox)
        self.comboModelo.setGeometry(QtCore.QRect(90, 197, 310, 27))
        self.comboModelo.setObjectName("comboModelo")

        self.retranslateUi(ventanaCargarInventario)
        QtCore.QMetaObject.connectSlotsByName(ventanaCargarInventario)

        self.comboEquipo.currentIndexChanged.connect(self.equipoSeleccionado)
        self.comboMarca.currentIndexChanged.connect(self.marcaSeleccionada)
        self.buttonImprimir.clicked.connect(self.imprimirInventario)
        self.buttonCancelar.clicked.connect(lambda:self.cerrarVentana(ventanaCargarInventario))

    def retranslateUi(self, ventanaCargarInventario):
        _translate = QtCore.QCoreApplication.translate
        ventanaCargarInventario.setWindowTitle(_translate("ventanaCargarInventario", "Inventario"))
        self.label.setText(_translate("ventanaCargarInventario", "Cliente:"))
        self.label_2.setText(_translate("ventanaCargarInventario", "Equipo:"))
        self.label_3.setText(_translate("ventanaCargarInventario", "Marca:"))
        self.label_4.setText(_translate("ventanaCargarInventario", "Modelo:"))
        self.buttonImprimir.setText(_translate("ventanaCargarInventario", "Imprimir"))
        self.buttonCancelar.setText(_translate("ventanaCargarInventario", "Cancelar"))

        self.inicializarVentana()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaCargarInventario = QtWidgets.QDialog()
    ui = Ui_VentanaCargarInventario()
    ui.setupUi(ventanaCargarInventario)
    ventanaCargarInventario.show()
    sys.exit(app.exec())
